export const happyLyrics = [
  ["[00:01.00]", "PAROLES 00:01.00"],
  ["[00:03.00]", "PAROLES 00:03.00"],
  ["[00:07.11]", "It might seem crazy what I am 'bout to say"],
  ["[00:13.10]", "Sunshine she's here, you can take a break"],
  ["[00:19.12]", "I'm a hot air balloon that could go to space"],
  ["[00:24.12]", "With the air, like I don't care, baby by the way"],
  ["[00:29.37]", "Huh (Because I'm happy)"],
  ["[00:31.61]", "Clap along if you feel like a room without a roof"],
  ["[00:35.61]", "(Because I'm happy)"],
  ["[00:37.10]", "Clap along if you feel like happiness is the truth"],
  ["[00:41.62]", "(Because I'm happy)"],
  ["[00:42.87]", "Clap along if you know what happiness is to you"],
  ["[00:47.64]", "(Because I'm happy)"],
  ["[00:49.12]", "Clap along if you feel like that's what you wanna do"],
  ["[00:55.12]", "Here come bad news talking this and that (Yeah)"],
  ["[01:01.11]", "Well give me all you got, don't hold back (Yeah)"],
  ["[01:06.66]", "Well I should probably warn you I'll be just fine (Yeah)"],
  ["[01:12.86]", "No offence to you don't waste your time"],
  ["[01:16.62]", "Here's why"],
  ["[01:18.12]", "Clap along if you feel like a room without a roof"],
  ["[01:23.87]", "(Because I'm happy)"],
  ["[01:25.11]", "Clap along if you feel like happiness is the truth"],
  ["[01:29.66]", "(Because I'm happy)"],
  ["[01:31.12]", "Clap along if you know what happiness is to you"],
  ["[01:35.88]", "(Because I'm happy)"],
  ["[01:37.16]", "Clap along if you feel like that's what you wanna do"],
  ["[01:42.87]", "Uh, bring me down"],
  ["[01:45.86]", "Can't nothing, bring me down"],
  ["[01:48.39]", "My level's too high to bring me down"],
  ["[01:50.87]", "Can't nothing, bring me down, I said"],
  ["[01:54.11]", "Bring me down, can't nothing"],
  ["[01:58.38]", "Bring me down"],
  ["[02:00.13]", "My level's too high to bring me down"],
  ["[02:01.89]", "Can't nothing, bring me down, I said"],
  ["[02:07.12]", "Clap along if you feel like a room without a roof"],
  ["[02:11.88]", "(Because I'm happy)"],
  ["[02:13.36]", "Clap along if you feel like happiness is the truth"],
  ["[02:17.61]", "(Because I'm happy)"],
  ["[02:19.12]", "Clap along if you know what happiness is to you"],
  ["[02:23.88]", "(Because I'm happy)"],
  ["[02:25.12]", "Clap along if you feel like that's what you wanna do"],
  ["[02:31.11]", "Clap along if you feel like a room without a roof"],
  ["[02:35.86]", "(Because I'm happy)"],
  ["[02:37.13]", "Clap along if you feel like happiness is the truth"],
  ["[02:41.85]", "(Because I'm happy)"],
  ["[02:43.12]", "Clap along if you know what happiness is to you"],
  ["[02:47.61]", "(Because I'm happy)"],
  ["[02:49.61]", "Clap along if you feel like that's what you wanna do"],
  ["[02:55.39]", "Uh, bring me down (Happy, happy, happy, happy)"],
  ["[02:57.12]", "Can't nothing (Happy, happy, happy, happy)"],
  ["[02:58.63]", "Bring me down, my level's too high"],
  ["[03:01.37]", "To bring me down (Happy, happy, happy, happy)"],
  ["[03:02.87]", "Can't nothing (Happy, happy, happy, happy)"],
  ["[03:04.62]", "Bring me down, I said"],
  ["[03:07.15]", "Clap along if you feel like a room without a roof"],
  ["[03:11.88]", "(Because I'm happy)"],
  ["[03:13.38]", "Clap along if you feel like happiness is the truth"],
  ["[03:17.87]", "(Because I'm happy)"],
  [
    "[03:19.62]",
    "Clap along if you know what happiness is to you (ayy, ayy, ayy)",
  ],
  ["[03:24.86]", "(Because I'm happy)"],
  ["[03:26.12]", "Clap along if you feel like that's what you wanna do"],
  ["[03:31.12]", "Clap along if you feel like a room without a roof"],
  ["[03:35.87]", "(Because I'm happy)"],
  ["[03:37.36]", "Clap along if you feel like happiness is the truth"],
  ["[03:41.64]", "(Because I'm happy)"],
  ["[03:43.62]", "Clap along if you know what happiness is to you (hey)"],
  ["[03:48.36]", "(Because I'm happy)"],
  ["[03:49.37]", "Clap along if you feel like that's what you wanna do"],
  ["[03:54.37]", "Come on"],
];

export const californicationLyrics = [
  ["[00:20.39]", "Psychic spies from China try to steal your mind's elation"],
  [
    "[00:25.39]",
    "And little girls from Sweden dream of silver-screen quotation",
  ],
  ["[00:30.29]", "And if you want these kind of dreams, it's Californication"],
  ["[00:45.03]", "It's the edge of the world and all of Western civilization"],
  [
    "[00:50.30]",
    "The sun may rise in the East, at least it settled in a final location",
  ],
  ["[00:55.54]", "It's understood that Hollywood sells Californication"],
  ["[01:10.54]", "Pay your surgeon very well to break the spell of aging"],
  [
    "[01:15.55]",
    "Celebrity skin: is this your chin or is that war you're waging?",
  ],
  ["[01:21.54]", "First born unicorn"],
  ["[01:25.42]", "Hardcore soft porn"],
  ["[01:30.17]", "Dream of Californication"],
  ["[01:34.92]", "Dream of Californication"],
  ["[01:39.92]", "Dream of Californication"],
  ["[01:44.93]", "Dream of Californication"],
  [
    "[02:00.17]",
    "Marry me, girl, be my fairy to the world, be my very own constellation",
  ],
  [
    "[02:04.92]",
    "A teenage bride with a baby inside getting high on information",
  ],
  ["[02:09.92]", "And buy me a star on the boulevard, it's Californication"],
  [
    "[02:24.92]",
    "Space may be the final frontier but it's made in a Hollywood basement",
  ],
  [
    "[02:29.93]",
    "And Cobain, can you hear the spheres singing songs off Station to Station?",
  ],
  ["[02:34.92]", "And Alderaan's not far away, it's Californication"],
  ["[02:50.18]", "Born and raised by those who praise control of population"],
  ["[02:54.67]", "Well, everybody's been there, and I don't mean no vacation"],
  ["[03:00.93]", "First born unicorn"],
  ["[03:05.33]", "Hardcore soft porn"],
  ["[03:09.57]", "Dream of Californication"],
  ["[03:14.32]", "Dream of Californication"],
  ["[03:19.33]", "Dream of Californication"],
  ["[03:24.32]", "Dream of Californication"],
  [
    "[04:19.07]",
    "Destruction leads to a very rough road but it also breeds creation",
  ],
  [
    "[04:23.58]",
    "And earthquakes are to a girl's guitar, they're just another good vibration",
  ],
  [
    "[04:28.57]",
    "And tidal waves couldn't save the world from Californication",
  ],
  ["[04:43.33]", "Pay your surgeon very well to break the spell of aging"],
  [
    "[04:48.32]",
    "Sicker than the rest, there is no test, but this is what you're craving",
  ],
  ["[04:54.32]", "First born unicorn"],
  ["[04:58.83]", "Hardcore soft porn"],
  ["[05:02.82]", "Dream of Californication"],
  ["[05:07.58]", "Dream of Californication"],
  ["[05:12.57]", "Dream of Californication"],
  ["[05:17.57]", "Dream of Californication"],
];

export const earfquakeLyrics = [
  ["[00:00.38]", "For real, for real this time"],
  ["[00:05.63]", "For real, for real, for real this time"],
  ["[00:09.88]", "Bitch, I cannot fall short"],
  ["[00:11.63]", "For real, for real, for real this time (yeah yeah)"],
  ["[00:17.63]", "For real, for real, for real this time"],
  ["[00:22.88]", "'Cause you make my earth quake"],
  ["[00:25.63]", "Oh, you make my earth quake"],
  [
    "[00:29.15]",
    "Riding around, your love is shakin' me up and it's making my heart break",
  ],
  ["[00:35.13]", "'Cause you make my earth quake (earth quake, ooh)"],
  ["[00:37.63]", "Oh, you make my earth quake"],
  [
    "[00:41.13]",
    "Riding around, your love is shakin' me up and it's making my heart break",
  ],
  ["[00:47.13]", "Don't leave, it's my fault"],
  ["[00:53.13]", "Don't leave, it's my fault"],
  ["[00:59.38]", "Don't leave, it's my fault (yeah)"],
  ["[01:05.13]", "'Cause when it all comes crashing down I'll need you"],
  ["[01:11.13]", "'Cause you make my earth quake"],
  ["[01:14.13]", "Oh, you make my earth quake"],
  [
    "[01:17.38]",
    "Riding around, you tell me something it's making my heart break",
  ],
  ["[01:23.38]", "'Cause you make my earth quake"],
  ["[01:26.15]", "Oh, you make my earth quake (earth quake, yeah)"],
  [
    "[01:29.38]",
    "Riding around, your love is shakin' me up and it's making my heart break (you already know)",
  ],
  ["[01:35.89]", "We ain't gotta ball, D.Rose, huh"],
  ["[01:37.37]", "Don't give a fuck 'bout nun', huh"],
  ["[01:38.88]", "Beamin' like fuck my lungs, huh"],
  ["[01:40.38]", "Just might call my lawyer, huh"],
  ["[01:41.87]", "Plug gon' set me up, huh"],
  ["[01:43.38]", "Bih, don't set me up, uh"],
  ["[01:44.88]", "I'm with Tyler, yuh (slime)"],
  ["[01:46.39]", "He ride like the car, huh"],
  ["[01:47.88]", "And she wicked, huh, yuh"],
  ["[01:49.38]", "Like Woah Vicky, huh, yeah (Like Woah Vicky)"],
  ["[01:50.88]", "Oh my God, hold up, um"],
  ["[01:52.63]", "These diamonds not Tiffany, huh, yeah"],
  ["[01:53.88]", "So in love"],
  ["[01:57.13]", "So in love"],
  ["[01:59.64]", "Don't leave, it's my fault (Fault)"],
  ["[02:05.63]", "Don't leave, it's my fault"],
  ["[02:11.63]", "Don't leave, it's my fault"],
  ["[02:17.38]", "'Cause when it all comes crashing down I'll need you"],
  ["[02:23.64]", "'cause you make my earth quake"],
  ["[02:25.39]", "I don't want no confrontation, no"],
  [
    "[02:28.13]",
    "You don't want my conversation (I don't want no conversation)",
  ],
  [
    "[02:31.38]",
    "I just need some confirmation on how you feel, for real (for real)",
  ],
  ["[02:37.13]", "(Ay) you don't want no complication, no"],
  [
    "[02:40.38]",
    "I don't want no sovereign nation (I don't want no sovereign nation)",
  ],
  ["[02:43.39]", "I don't even know 'bout that 'cause I'm for real (for real)"],
  ["[02:47.63]", "I said don't leave, it's my fault (one)"],
  ["[02:53.38]", "I said don't leave, it's my fault (two, two)"],
  ["[02:59.88]", "Don't leave, its, it's my fault girl (one, two, three)"],
  ["[03:05.88]", "Don't, do-do-do-do-do, I need"],
];

export const hurricaneLyrics = [
  ["[00:01.18]", "See this in 3D, all lights out for me"],
  ["[00:07.19]", "All lights out for me, lightning strikes the beach"],
  ["[00:13.44]", "80 degrees, warm it up for me"],
  ["[00:19.19]", "Finally free, found the God in me"],
  ["[00:24.72]", "And I want you to see, I can walk on water"],
  ["[00:31.47]", "Thousand miles from shore, I can float on the water"],
  ["[00:37.47]", "Father, hold me close, don't let me drown"],
  ["[00:43.23]", "I know you won't"],
  [
    "[00:46.27]",
    "Yeah, walking on the bridge, I threw my sins over the deep end",
  ],
  [
    "[00:49.52]",
    "Sipping 'til my stomach hurt, this month I done lost three friends",
  ],
  ["[00:52.51]", "Early morning, brainstorming, normally I can't sleep in"],
  ["[00:55.51]", "Sometimes I just wanna restart it, but it all depends"],
  ["[00:58.26]", "If I'ma be the same young hungry - from West End"],
  [
    "[01:01.26]",
    "Wrote my hardest wrongs and the crazy part, I ain't have no pen",
  ],
  ["[01:04.51]", "Maybach interior came with sheepskin"],
  ["[01:06.76]", "Still remember when I just had three bands"],
  ["[01:09.01]", "Now I'm the one everyone calling on 'cause I got deep pants"],
  ["[01:12.01]", "Bro' told me to wait to beat the game, it's all in defense"],
  [
    "[01:14.51]",
    "And never fazed by names that they might call me, but they gon' respect it",
  ],
  [
    "[01:18.01]",
    "And I feel like you better off tryin' to call, I might not get the message",
  ],
  [
    "[01:21.04]",
    "And she just tried to run off with my heart, but I blocked off the exit, yeah",
  ],
  ["[01:25.80]", "Oh-oh, I know You won't, I know You won't, I know You won't"],
  ["[01:37.33]", "I know You won't, I know that You look over us"],
  ["[01:43.07]", "So we silently sleep"],
  ["[01:49.82]", "Bring down the rain, yeah, oh-oh"],
  ["[02:01.07]", "Mm-mm-mm, mm-mm, I was out for self"],
  ["[02:04.12]", "Mm-mm-mm, mm-mm, I was up for sale"],
  ["[02:07.12]", "But I couldn't tell"],
  ["[02:08.63]", "God made it rain, the devil made it hell"],
  ["[02:11.62]", "Dropped out of school, but I'm that one at Yale"],
  ["[02:14.62]", "Made the best tracks and still went off the rail"],
  ["[02:17.65]", "Hat go down, down, down, this the new town, town, town"],
  ["[02:20.39]", "This the new ten, ten, ten, I'm going in, in, in"],
  ["[02:23.39]", "Here I go on a new trip, here I go acting too lit"],
  ["[02:26.14]", "Here I go acting too rich, here I go with a new chick"],
  ["[02:29.39]", "And I know what the truth is, still playing after two kids"],
  ["[02:32.42]", "It's a lot to digest when your life always moving"],
  ["[02:35.42]", "Architectural Digest, but I needed home improvement"],
  ["[02:38.42]", "60 million dollar home, never went home to it"],
  ["[02:41.69]", "Genius gone clueless, it's a whole lot to risk"],
  ["[02:44.43]", "Alcohol Anonymous, who's the busiest loser?"],
  ["[02:47.68]", "Heated by the rumors, read into it too much"],
  ["[02:50.68]", 'Fiending for some true love, ask Kim, "What did you love?"'],
  [
    "[02:53.43]",
    "Hard to find what the truth is, but the truth was that the truth suck",
  ],
  ["[02:56.71]", "Always seem to do stuff, but this time it was too much"],
  ["[02:59.46]", "Mm-mm-mm, mm-mm, everybody so judgmental"],
  ["[03:04.24]", "Everybody so judgmental"],
  ["[03:06.21]", "Everybody hurts, but I don't judge rentals"],
  ["[03:08.50]", "Mm-mm-mm, mm-mm, it was all so simple"],
  ["[03:13.49]", "I see you in 3D, the dawn is bright for me"],
  ["[03:19.50]", "No more dark for me, I know you're watching me"],
  ["[03:25.50]", "80 degrees, burning up the leaves"],
  ["[03:30.99]", "Finally, I'm free, finally, I'm free"],
  ["[03:36.77]", "As I go out to sea, I can walk on water"],
  ["[03:43.52]", "Won't you shine Your light? Demons stuck on my shoulder"],
  ["[03:49.28]", "Father, hold me close, don't let me drown"],
  ["[03:55.53]", "I know you won't"],
];
